/* Presentation helpers. No API requests or changes to saved data formats. */
(() => {
  const $ = s => document.querySelector(s);
  const events = [];
  const stack = document.createElement('div'); stack.className = 'toast-stack'; stack.setAttribute('aria-live','polite'); stack.setAttribute('aria-atomic','false'); document.body.append(stack);
  const main = $('main') || $('.auth-card');
  if(main){if(!main.id) main.id='mainContent';const skip=document.createElement('a');skip.className='skip-link';skip.href='#'+main.id;skip.textContent='Skip to main content';document.body.prepend(skip);main.tabIndex=-1;}
  const nav=$('.dashboard-nav');
  if(nav){const wrap=document.createElement('div');wrap.className='notification-wrap';wrap.innerHTML='<button type="button" class="icon-btn notification-button" aria-label="Notifications" aria-expanded="false" aria-controls="notificationPanel"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 20h6"/></svg><span class="notification-count" hidden></span></button><section id="notificationPanel" class="notification-panel" aria-label="Notifications" hidden><h2>Notifications</h2><p>Updates from this page. Your study materials stay saved.</p><ul class="notification-list"></ul><div class="notification-empty">You’re all caught up.</div></section>';nav.insertBefore(wrap,nav.children[1]||null);const button=wrap.querySelector('button'),panel=wrap.querySelector('section');const close=()=>{panel.hidden=true;button.setAttribute('aria-expanded','false');};button.onclick=()=>{panel.hidden=!panel.hidden;button.setAttribute('aria-expanded',String(!panel.hidden));wrap.querySelector('.notification-count').hidden=true;};document.addEventListener('click',e=>{if(!wrap.contains(e.target))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden){close();button.focus();}});}
  function notify(message,kind='info'){
    if(!message)return;
    if([...stack.children].some(t=>t.firstChild?.textContent===message))return;
    events.unshift({message,time:new Date()});events.splice(15);
    const list=$('.notification-list');if(list){list.replaceChildren();for(const event of events){const li=document.createElement('li');li.textContent=event.message;const time=document.createElement('small');time.textContent=event.time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});li.append(time);list.append(li);}$('.notification-empty').hidden=true;const count=$('.notification-count');count.textContent=String(events.length);count.hidden=!$('#notificationPanel').hidden;}
    const toast=document.createElement('div');toast.className='sg-toast';toast.dataset.kind=kind;toast.setAttribute('role',kind==='error'?'alert':'status');const text=document.createElement('span');text.textContent=message;const close=document.createElement('button');close.type='button';close.setAttribute('aria-label','Dismiss notification');close.textContent='×';close.onclick=()=>toast.remove();toast.append(text,close);stack.append(toast);while(stack.children.length>3)stack.firstChild.remove();let timer=setTimeout(()=>toast.remove(),8000);toast.addEventListener('mouseenter',()=>clearTimeout(timer));toast.addEventListener('focusin',()=>clearTimeout(timer));const resume=()=>{clearTimeout(timer);timer=setTimeout(()=>toast.remove(),8000);};toast.addEventListener('mouseleave',resume);toast.addEventListener('focusout',resume);
  }
  function paginate(form){
    if(!form||form.dataset.paginated)return;form.dataset.paginated='true';form.noValidate=true;
    const questions=[...form.querySelectorAll('.quiz-question')],submit=form.querySelector('button[type="submit"]');if(!questions.length||!submit)return;
    let index=0;const progress=document.createElement('div');progress.className='quiz-progress';progress.innerHTML='<span aria-live="polite"></span><progress value="0" max="'+questions.length+'" aria-label="Questions answered"></progress>';
    const jumps=document.createElement('div');jumps.className='quiz-jumps';jumps.setAttribute('aria-label','Question navigation');const pager=document.createElement('div');pager.className='quiz-pager';const previous=document.createElement('button'),next=document.createElement('button');previous.type=next.type='button';previous.className='secondary-btn';next.className='primary-btn';previous.textContent='← Previous';next.textContent='Next question →';pager.append(previous,next,submit);form.prepend(progress,jumps);form.append(pager);
    const answered=q=>!!q.querySelector('input:checked');
    questions.forEach((q,i)=>{const jump=document.createElement('button');jump.type='button';jump.textContent=i+1;jump.setAttribute('aria-label','Go to question '+(i+1));jump.onclick=()=>{index=i;draw(true);};jumps.append(jump);q.querySelector('legend').tabIndex=-1;});
    function draw(focus=false){questions.forEach((q,i)=>{q.hidden=i!==index;jumps.children[i].classList.toggle('answered',answered(q));jumps.children[i].setAttribute('aria-current',String(i===index));});const count=questions.filter(answered).length;progress.querySelector('span').textContent=`Question ${index+1} of ${questions.length} · ${count} answered`;progress.querySelector('progress').value=count;previous.disabled=index===0;next.hidden=index===questions.length-1;submit.hidden=index!==questions.length-1;if(focus)questions[index].querySelector('legend').focus({preventScroll:true});}
    previous.onclick=()=>{index=Math.max(0,index-1);draw(true);};next.onclick=()=>{if(!answered(questions[index])){notify('Choose an answer before continuing.');questions[index].querySelector('input').focus();return;}index=Math.min(questions.length-1,index+1);draw(true);};form.addEventListener('change',()=>draw());
    form.addEventListener('submit',e=>{const missing=questions.findIndex(q=>!answered(q));if(missing!==-1){e.preventDefault();e.stopImmediatePropagation();index=missing;draw(true);notify('Answer each question before submitting.');}},true);draw();
  }
  function analytics(target,attempt){
    if(!target||!attempt)return;const stats=document.createElement('section');stats.className='result-stats';stats.setAttribute('aria-label','Quiz results');for(const [label,value] of [['Correct',attempt.score],['To revisit',Math.max(0,attempt.total-attempt.score)],['Accuracy',attempt.percentage+'%']]){const cell=document.createElement('div');cell.textContent=label;const strong=document.createElement('strong');strong.textContent=value;cell.append(strong);stats.append(cell);}const score=target.querySelector('.quiz-score');if(score)score.after(stats);else target.prepend(stats);
  }
  function processing(state){const box=$('#processing');if(!box)return;box.classList.remove('hidden','is-processing','is-complete','is-error');box.classList.add('is-'+state);const label=$('#processingLabel'),bar=box.querySelector('[role="progressbar"]');$('#progressPct').textContent=state==='complete'?'Ready':state==='error'?'Interrupted':'In progress';label.textContent=state==='complete'?'Your lecture is ready.':state==='error'?'We couldn’t finish this lecture.':'Preparing your transcript and notes…';if(state==='processing')bar.removeAttribute('aria-valuenow');else{bar.setAttribute('aria-valuenow',state==='complete'?'100':'0');bar.setAttribute('aria-valuemin','0');bar.setAttribute('aria-valuemax','100');}}
  window.StudyUI={notify,paginate,analytics,processing};
  const input=$('#lectureUrl');if(input){input.addEventListener('input',()=>{const hint=$('#lectureDetection');hint.className='lecture-detection';if(!input.value.trim()){hint.textContent='Paste a YouTube link to get started.';return;}try{const url=new URL(input.value.trim());const host=url.hostname.replace(/^www\.|^m\./,'');const id=host==='youtu.be'?url.pathname.slice(1):['youtube.com','youtube-nocookie.com'].includes(host)?url.searchParams.get('v')||url.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/)?.[1]:null;if(!['https:','http:'].includes(url.protocol)||!id||!/^[\w-]{11}$/.test(id))throw Error();hint.classList.add('is-valid');hint.textContent='✓ YouTube link recognized · Lecture details will be checked when you generate.';}catch{hint.classList.add('is-invalid');hint.textContent='Enter a complete YouTube video link. We’ll verify it when you generate.';}});}
  for(const id of ['settingsMessage','saveMsg']){const node=document.getElementById(id);if(node){node.setAttribute('role','status');new MutationObserver(()=>{if(node.textContent.trim()&&!node.classList.contains('hidden'))notify(node.textContent.trim(),/saved|updated/i.test(node.textContent)?'success':'info');}).observe(node,{childList:true,subtree:true,characterData:true});}}
  const profile=$('#profileBtn');if(profile){profile.setAttribute('aria-expanded','false');profile.setAttribute('aria-controls','profileMenu');new MutationObserver(()=>profile.setAttribute('aria-expanded',String($('#profileMenu').classList.contains('show')))).observe($('#profileMenu'),{attributes:true,attributeFilter:['class']});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#profileMenu').classList.contains('show')){$('#profileMenu').classList.remove('show');profile.focus();}});}
})();
